# Generated by Django 4.2.2 on 2023-06-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloud_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afternoon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afternoon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0)),
                ('lon', models.IntegerField(default=0)),
                ('tz', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('units', models.CharField(max_length=100)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.cloud_cover')),
            ],
        ),
        migrations.CreateModel(
            name='MaxV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=2)),
                ('direction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afternoon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=2)),
                ('max', models.DecimalField(decimal_places=2, max_digits=2)),
                ('afternoon', models.DecimalField(decimal_places=2, max_digits=2)),
                ('night', models.DecimalField(decimal_places=2, max_digits=2)),
                ('evening', models.DecimalField(decimal_places=2, max_digits=2)),
                ('morning', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.maxv')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humidity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.humidity')),
                ('Location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.location')),
                ('Precipitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.precipitation')),
                ('Pressure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.pressure')),
                ('Temperature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.temperature')),
                ('Wind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.wind')),
            ],
        ),
    ]
