# Generated by Django 4.2.2 on 2023-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_location_relation_delete_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxv',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
